// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBktFbBxL1kvZefeVBbWSZOSQZIb8rLYqY',
    appId: '1:1062517539608:web:7d61e47b8ea54fa641546d',
    messagingSenderId: '1062517539608',
    projectId: 'gymflow-dalai',
    authDomain: 'gymflow-dalai.firebaseapp.com',
    storageBucket: 'gymflow-dalai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAReAMQx8F5tAj9Plosx_Fl3E1FXkIiE-U',
    appId: '1:1062517539608:android:da297075359b5e4641546d',
    messagingSenderId: '1062517539608',
    projectId: 'gymflow-dalai',
    storageBucket: 'gymflow-dalai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkYFbbYus1MroF0stOhDYXXIETnj3Pql8',
    appId: '1:1062517539608:ios:2216c5665aa3c36441546d',
    messagingSenderId: '1062517539608',
    projectId: 'gymflow-dalai',
    storageBucket: 'gymflow-dalai.firebasestorage.app',
    iosBundleId: 'com.example.gymflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkYFbbYus1MroF0stOhDYXXIETnj3Pql8',
    appId: '1:1062517539608:ios:2216c5665aa3c36441546d',
    messagingSenderId: '1062517539608',
    projectId: 'gymflow-dalai',
    storageBucket: 'gymflow-dalai.firebasestorage.app',
    iosBundleId: 'com.example.gymflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBktFbBxL1kvZefeVBbWSZOSQZIb8rLYqY',
    appId: '1:1062517539608:web:b4fbdbb881f9898441546d',
    messagingSenderId: '1062517539608',
    projectId: 'gymflow-dalai',
    authDomain: 'gymflow-dalai.firebaseapp.com',
    storageBucket: 'gymflow-dalai.firebasestorage.app',
  );
}



